# Generated by Django 4.1.7 on 2023-05-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_created_at'),
        ('tasks', '0007_tasklabels_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabels',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label'),
        ),
    ]
